heat_template_version: 2013-05-23

description: A Windows Snapshot server.
parameters:
  server_name:
    type: string
    default: Name of the instance
  flavor:
    type: string
    default: m1.medium, m1.large, m1.xlarge, m1.2xlarge, m1.4xlarge
  public_net_id:
    type: string
    label: Public Network ID
    default: PUBLIC NETWORK ID or NAME
  private_network:
    type: string
    label: Private Network ID
    default: PRIVATE NETWORK ID or NAME
  private_subnet:
    type: string
    label: Private Sub Network ID
    default: PRIVATE SUB-NET ID or NAME
  vol_snapshot_id:
    type: string
    default: VOLUME SNAPSHOT ID
  vol_size:
    type: string
    label: Volume Size
    default: 50 

resources:
  server:
    type: OS::Nova::Server
    properties:
      block_device_mapping:
        - device_name: vda
          delete_on_termination: false
          volume_id: { get_resource: volume }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: instance1_port }
      name : { get_param: server_name }
      user_data_format: RAW
      user_data:
        str_replace:
             params:
                __private_network__: { get_param: private_network }
                __flavor__: { get_param: flavor }
                __public_net_id__ : {get_param: public_net_id }
                __private_subnet__ : {get_param : private_subnet }
             template : |
               #ps1
               sysprep  /oobe /generalize /reboot
               mkdir c:\tenant
               echo "Priavte Network __private_network__ Flavor __flavor__ Public Net Id __public_net_id__ Private Subnet __private_subnet__" >> c:\tenant\tenant_info.txt

  instance1_port:
     type: OS::Neutron::Port
     properties:
       network_id: { get_param: private_network }
       fixed_ips:
         - subnet_id: { get_param: private_subnet }
       security_groups: [{get_resource: server_security_group }]
  instance1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: instance1_port }

  server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: windows-security-group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 1
          port_range_max: 65535
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
  volume:
    type: OS::Cinder::Volume
    properties:
      snapshot_id:
      snapshot_id: { get_param: vol_snapshot_id }
      size: { get_param: vol_size }
