heat_template_version: 2013-05-23

description: |
  Heat Orchestration Template that spins up a resource group with multiple cloud servers.

parameters:
  number_of_vms:
    type: string
    default: 2
  image:
    type: string
    default: win2812.raw, win2k12.raw
  instance_name:
    type: string
    default: Name of the instance
  flavor:
    type: string
    default: m1.medium, m1.large, m1.xlarge, m1.2xlarge, m1.4xlarge
    constraints:
      - allowed_values: [ m1.xlarge, m1.medium, m1.small, m1.4xlarge, m1.2xlarge, m1.large  ]
  public_net_id:
    type: string
    default: PUBLIC NETWORK ID or NAME
  private_network:
    type: string
    default: PRIVATE NETWORK ID or NAME
  private_subnet:
    type: string
    default: PRIVATE SUB-NET ID or NAME
  vol_size:
    type: string
    default: 50

resources:
  my_nodes:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: number_of_vms }
      resource_def: 
        type: 'http://<IPADDRESS>:8080/xyz/abcd.yaml'
        properties:
          instance_name: { get_param: instance_name }
          flavor: { get_param: flavor }
          public_net_id: { get_param: public_net_id }
          private_network: { get_param: private_network }
          private_subnet: { get_param: private_subnet }
          vol_size: { get_param: vol_size }

