heat_template_version: 2014-10-16

description: SFTP Server 

parameters:
  INSTANCE_NAME:
    type: string
    description : Name of the instance
  Image_Name:
    type: string
    description: Image use to boot a server
    default: Ubuntu1404, Ubuntu1204, Oracle-Linux7.1, Centos7.2
  Public_Network_ID:
    type: string
    default: PUBLIC NETWORK ID or NAME
  Private_Network_ID:
    type: string
    default: PRIVATE NETWORK ID or NAME
  Private_Network_Subnet_ID:
    type: string
    default: PRIVATE SUB-NET ID or NAME
  Key_Pair_Name:
    type: string
    default: CloudOperations
  Flavor_Name:
    type: string
    label: Flavor
    description: Type of instance (flavor) to be used on the compute instance.
    default: m1.medium, m1.large, m1.xlarge, m1.2xlarge, m1.4xlarge
  vol_size:
    type: string
    default: 20
  
  
resources:
  server:
    type: OS::Nova::Server
    properties:
      block_device_mapping:
        - device_name: vda
          delete_on_termination: false
          volume_id: { get_resource: volume }
      key_name: { get_param: Key_Pair_Name }
      flavor: { get_param: Flavor_Name }
      networks:
        - port: { get_resource: instance_port }
      name: { get_param: INSTANCE_NAME }
      user_data: | 
        #!/bin/bash -v
        sudo groupadd sftpaccess
        sed -i 's/Subsystem/#Subsystem/g' /etc/ssh/sshd_config
        sed -i 's/X11Forwarding/#X11Forwarding/g' /etc/ssh/sshd_config
        sed -i 's/PermitRootLogin/#PermitRootLogin/g' /etc/ssh/sshd_config
        sed -i 's/HostbasedAuthentication/#HostbasedAuthentication/g' /etc/ssh/sshd_config
        sed -i 's/PasswordAuthentication/#PasswordAuthentication/g' /etc/ssh/sshd_config
        sed -i 's/Port/#Port/g' /etc/ssh/sshd_config
        cat <<EOT >> /etc/ssh/sshd_config
        Port 5109
        PermitRootLogin no
        HostbasedAuthentication yes
        PasswordAuthentication yes
        Subsystem sftp internal-sftp
        Match group sftpaccess
        ChrootDirectory %h
        X11Forwarding no
        AllowTCPForwarding no
        ForceCommand internal-sftp
        EOT
        sudo service ssh restart
        sudo adduser sftp-user --ingroup sftpaccess -shell /usr/sbin/nologin
        sudo chown root:root /home/sftp-user
        sudo mkdir -p /home/sftp-user/public
        sudo chown sftp-user:sftpaccess /home/sftp-user/public
  volume:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: Image_Name }
      size: { get_param: vol_size }
  instance_port:
     type: OS::Neutron::Port
     properties:
       network_id: { get_param: Private_Network_ID }
       fixed_ips:
         - subnet_id: { get_param: Private_Network_Subnet_ID }
       security_groups: [{get_resource: server_security_group }]
  instance_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: Public_Network_ID }
      port_id: { get_resource: instance_port }
  server_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for server
      name: SFTPGroup
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
          port_range_min: 22
          port_range_max: 22
          port_range_min: 5109
          port_range_max: 5109
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
outputs:
  server_private_ip:
     description: IP address of the server in the private network
     value: { get_attr: [ server, first_address ] }

